const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.gamepad,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Turret,
		C3.Behaviors.Pin,
		C3.Behaviors.TileMovement,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.TileMovement.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.ClearTargets,
		C3.Plugins.gamepad.Cnds.IsButtonDown
	];
};
self.C3_JsPropNameTable = [
	{selectScreenblur: 0},
	{icon_sol: 0},
	{icon_link: 0},
	{selectBackground: 0},
	{Label: 0},
	{p1Select: 0},
	{p2Select: 0},
	{P1_name: 0},
	{P2_name: 0},
	{p1Silhouette: 0},
	{p2Silhouette: 0},
	{Mouse: 0},
	{Áudio: 0},
	{startButton: 0},
	{buttonPress: 0},
	{mapBackground: 0},
	{mapScene: 0},
	{playebleSolP1: 0},
	{playableLinkP1: 0},
	{lastRightTapTime: 0},
	{lastLeftTapTime: 0},
	{dashCooldown: 0},
	{Plataforma: 0},
	{Cronômetro: 0},
	{Interpolação: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{spawnP1: 0},
	{lastRightTapTime2: 0},
	{lastLeftTapTime2: 0},
	{dashCooldown2: 0},
	{spawnP2: 0},
	{loading: 0},
	{Gamepad: 0},
	{Teclado: 0},
	{PularAtravés: 0},
	{Sólido: 0},
	{mapFloor: 0},
	{DestruirForaDoLayout: 0},
	{p1CollisionBox: 0},
	{UIP1: 0},
	{UIP2: 0},
	{UIsilhouetteP1: 0},
	{UIsilhouetteP2: 0},
	{healthscoreP1: 0},
	{UIhealthP1: 0},
	{healthscoreP2: 0},
	{UIhealthP2: 0},
	{p1KnockbackCollisionBox: 0},
	{Magic: 0},
	{ringout: 0},
	{deathwall: 0},
	{center: 0},
	{dashSmoke: 0},
	{p1HardKnockbackCollisionBox: 0},
	{UILifeP1: 0},
	{UILifeP2: 0},
	{wins: 0},
	{arrow: 0},
	{Projétil: 0},
	{p1Projectile: 0},
	{Charge: 0},
	{hit: 0},
	{playableLinkP2: 0},
	{playebleSolP2: 0},
	{p2CollisionBox: 0},
	{p2HardKnockbackCollisionBox: 0},
	{p2KnockbackCollisionBox: 0},
	{p2Projectile: 0},
	{game: 0},
	{debugConnected: 0},
	{debugHitting: 0},
	{debugCombo: 0},
	{debugCutscene: 0},
	{debugHitting2: 0},
	{debugCombo2: 0},
	{debugConnected2: 0},
	{debugCutscene2: 0},
	{icon_yugi: 0},
	{icon_seiya: 0},
	{playableYugiP1: 0},
	{Canhão: 0},
	{p1Summon: 0},
	{p1cd1: 0},
	{p1cd2: 0},
	{p2cd1: 0},
	{p2cd2: 0},
	{p1cd3: 0},
	{p2cd3: 0},
	{p2Summon: 0},
	{playableYugiP2: 0},
	{mapFloorTexture: 0},
	{mapPlataform: 0},
	{playebleWeskP1: 0},
	{icon_wesker: 0},
	{playebleWeskP2: 0},
	{playableSeiyaP1: 0},
	{playableSeiyaP2: 0},
	{Fixar: 0},
	{player1arrow: 0},
	{player2arrow: 0},
	{MovimentoEmGrid: 0},
	{player2arrowbox: 0},
	{player1arrowbox: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{tutorial: 0},
	{tutorial2: 0},
	{tutorial3: 0},
	{tutorial4: 0},
	{playerActive: 0},
	{CharacterP1: 0},
	{CharacterP2: 0},
	{p1Connected: 0},
	{p1ComboCount: 0},
	{p1isHitting: 0},
	{p1inCutscene: 0},
	{p2Connected: 0},
	{p2ComboCount: 0},
	{p2isHitting: 0},
	{p2inCutscene: 0},
	{p1win: 0},
	{p2win: 0},
	{mapChoose: 0}
];

self.InstanceType = {
	selectScreenblur: class extends self.ISpriteInstance {},
	icon_sol: class extends self.ISpriteInstance {},
	icon_link: class extends self.ISpriteInstance {},
	selectBackground: class extends self.ISpriteInstance {},
	Label: class extends self.ISpriteInstance {},
	p1Select: class extends self.ISpriteInstance {},
	p2Select: class extends self.ISpriteInstance {},
	P1_name: class extends self.ITextInstance {},
	P2_name: class extends self.ITextInstance {},
	p1Silhouette: class extends self.ISpriteInstance {},
	p2Silhouette: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	startButton: class extends self.ISpriteInstance {},
	buttonPress: class extends self.ISpriteInstance {},
	mapBackground: class extends self.ISpriteInstance {},
	mapScene: class extends self.ISpriteInstance {},
	playebleSolP1: class extends self.ISpriteInstance {},
	playableLinkP1: class extends self.ISpriteInstance {},
	spawnP1: class extends self.ISpriteInstance {},
	spawnP2: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	mapFloor: class extends self.ITiledBackgroundInstance {},
	p1CollisionBox: class extends self.ISpriteInstance {},
	UIP1: class extends self.ISpriteInstance {},
	UIP2: class extends self.ISpriteInstance {},
	UIsilhouetteP1: class extends self.ISpriteInstance {},
	UIsilhouetteP2: class extends self.ISpriteInstance {},
	UIhealthP1: class extends self.ITextInstance {},
	UIhealthP2: class extends self.ITextInstance {},
	p1KnockbackCollisionBox: class extends self.ISpriteInstance {},
	Magic: class extends self.ISpriteInstance {},
	ringout: class extends self.ISpriteInstance {},
	deathwall: class extends self.ISpriteInstance {},
	center: class extends self.ISpriteInstance {},
	dashSmoke: class extends self.ISpriteInstance {},
	p1HardKnockbackCollisionBox: class extends self.ISpriteInstance {},
	UILifeP1: class extends self.ISpriteInstance {},
	UILifeP2: class extends self.ISpriteInstance {},
	wins: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	p1Projectile: class extends self.ISpriteInstance {},
	Charge: class extends self.ISpriteInstance {},
	hit: class extends self.ISpriteInstance {},
	playableLinkP2: class extends self.ISpriteInstance {},
	playebleSolP2: class extends self.ISpriteInstance {},
	p2CollisionBox: class extends self.ISpriteInstance {},
	p2HardKnockbackCollisionBox: class extends self.ISpriteInstance {},
	p2KnockbackCollisionBox: class extends self.ISpriteInstance {},
	p2Projectile: class extends self.ISpriteInstance {},
	game: class extends self.ISpriteInstance {},
	debugConnected: class extends self.ITextInstance {},
	debugHitting: class extends self.ITextInstance {},
	debugCombo: class extends self.ITextInstance {},
	debugCutscene: class extends self.ITextInstance {},
	debugHitting2: class extends self.ITextInstance {},
	debugCombo2: class extends self.ITextInstance {},
	debugConnected2: class extends self.ITextInstance {},
	debugCutscene2: class extends self.ITextInstance {},
	icon_yugi: class extends self.ISpriteInstance {},
	icon_seiya: class extends self.ISpriteInstance {},
	playableYugiP1: class extends self.ISpriteInstance {},
	p1Summon: class extends self.ISpriteInstance {},
	p1cd1: class extends self.ISpriteInstance {},
	p1cd2: class extends self.ISpriteInstance {},
	p2cd1: class extends self.ISpriteInstance {},
	p2cd2: class extends self.ISpriteInstance {},
	p1cd3: class extends self.ISpriteInstance {},
	p2cd3: class extends self.ISpriteInstance {},
	p2Summon: class extends self.ISpriteInstance {},
	playableYugiP2: class extends self.ISpriteInstance {},
	mapFloorTexture: class extends self.ISpriteInstance {},
	mapPlataform: class extends self.ISpriteInstance {},
	playebleWeskP1: class extends self.ISpriteInstance {},
	icon_wesker: class extends self.ISpriteInstance {},
	playebleWeskP2: class extends self.ISpriteInstance {},
	playableSeiyaP1: class extends self.ISpriteInstance {},
	playableSeiyaP2: class extends self.ISpriteInstance {},
	player1arrow: class extends self.ISpriteInstance {},
	player2arrow: class extends self.ISpriteInstance {},
	player2arrowbox: class extends self.ISpriteInstance {},
	player1arrowbox: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	tutorial: class extends self.ITextInstance {},
	tutorial2: class extends self.ITextInstance {},
	tutorial3: class extends self.ITextInstance {},
	tutorial4: class extends self.ITextInstance {}
}